apiVersion: pdok.nl/v1alpha1
kind: OGCAPI
metadata:
  labels:
    app.kubernetes.io/name: ogcapi
    app.kubernetes.io/instance: ogcapi-sample
    app.kubernetes.io/part-of: ogcapi-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ogcapi-operator
  name: ogcapi-sample
spec:
  # TODO(user): Add fields here
